name: Cypress tests
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      # Use Cypress GitHub action to run tests
      # https://github.com/cypress-io/github-action
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn dev
        # Environment variables for Ley and Next.js
        # to be able to connect to the database
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          DB_NAME: ${{ secrets.DB_NAME }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
          CYPRESS_test_email: ${{secrets.CYPRESS_test_email}}
          CYPRESS_test_password: ${{secrets.CYPRESS_test_password}}
